//Items

var items = [
    "Planks",
    "stick",
    "torch",
    "workbench",
    "chest",
    "furnace",
    "ladder",
    "fence",
    "boat",
    "wooden slabs",
    "stone slabs",
    "sign",
    "doors",
    "painting",
    "bed",
    "wood",
    "pickaxes",
    "shovels",
    "axe",
    "hoes",
    "fishing rod",
    "flint and steel",
    "shears",
    "bucket",
    "clock",
    "compass",
    "map",
    "shulker box",
    "paper",
    "book",
    "book and quill",
    "iron bars",
    "nether brick fence",
    "gold ingot",
    "eye of ender",
    "enchantment table",
    "fire charge",
    "ender chest",
    "beacon",
    "anvil",
    "flower pot",
    "item frame",
    "carrot on a stick",
    "warped fungus on a stick",
    "fire work rocket",
    "fire work star",
    "lead",
    "carpets",
    "glass panes",
    "lead her",
    "banner",
    "armor stand",
    "end rod",
    "end crystal",
    "iron nugget",
    "concrete powder",
    "campfire",
    "soul campfire",
    "scaffolding",
    "barrel",
    "blast furnace",
    "smoker",
    "cartography table",
    "composter",
    "fletching table",
    "smithing table",
    "stonecutter",
    "grindstone",
    "lanterns",
    "lectern",
    "loom",
    "beehive",
    "chain",
    "netherite ingot",
    "soul torch",
    "respawn anchors",
    "loadstone",
    "helmets",
    "chestplates",
    "leggings",
    "boots",
    "swords",
    "bow",
    "crossbow",
    "arrow",
    "horse armor",
    "shield",
    "spectral arrow",
    "tipped arrow",
    "conduit",
    "turtle shell",
    "glass bottle",
    "cauldron",
    "brewing stand",
    "glistering melon",
    "blaze powder",
    "fermented spider eye",
    "magma cream",
    "pressure plates",
    "weighted pressure plates",
    "lever",
    "buttons",
    "trapdoor",
    "piston",
    "sticky piston",
    "fence gate",
    "Redstone repeater",
    "dispenser",
    "jukebox",
    "minecart",
    "powered minecart",
    "minecart with TNT",
    "storage minecart",
    "track",
    "powered rail",
    "detector rail",
    "activator rail",
    "Redstone torch",
    "Redstone lamp",
    "tripwire hook",
    "daylight sensor",
    "dropper",
    "hopper",
    "Redstone comparator",
    "trapped chest",
    "iron trapdoor",
    "observer",
    "target",
    "glow stone",
    "snow block",
    "stone brick",
    "brick",
    "sandstone",
    "smooth sandstone",
    "decorative sandstone",
    "gold block",
    "diamond block",
    "iron block",
    "lapis lazuli block",
    "emerald block",
    "coal block",
    "wool block",
    "bookshelf",
    "note block",
    "clay block",
    "jack lantern",
    "TNT",
    "wooden stairs",
    "stone stairs",
    "cobblestone walls",
    "block of Redstone",
    "nether brick",
    "red nether brick",
    "chiseled nether brick",
    "nether wart block",
    "block of quartz",
    "chiseled quarts block",
    "pillar quarts block",
    "quartz brick",
    "hay bale",
    "stained clay",
    "stained glass",
    "granite",
    "andesite",
    "diorite",
    "polished granite",
    "polished andesite",
    "polished diorite",
    "prismarine",
    "prismarine bricks",
    "dark prismarine",
    "sea lantern",
    "coarse dirt",
    "slime block",
    "moss stone",
    "mossy stone brick",
    "chiseled stone brick",
    "red sandstone",
    "smooth red sandstone",
    "chiseled red sand",
    "purpur block",
    "purpur pillar",
    "magma block",
    "bone block",
    "dried kelp block",
    "packed ice",
    "blue ice",
    "honey block",
    "Honeycomb block",
    "stripped wood",
    "polished basait",
    "polished black stone",
    "chiseled polished black stone",
    "polished black stone brick",
    "block of netherite",
    "cake",
    "bread",
    "cookie",
    "bowl",
    "mushroom stew",
    "golden apple",
    "golden carrot",
    "Pumkin seeds",
    "melon seeds",
    "melon block",
    "sugar",
    "pumkin pie",
    "rabbit stew",
    "suspicious stew",
    "",
]

var itemsDetails = ["Planks are very common"]

var itemsP = ["تخته چوب", "چوب", " کبریت", "میز کار", "صندوق", "کوره", "نردبان", "حصار", "قایق", "اسلب چوبی", "اسلب سنگی", "تابلو", "در", "نقاشی", "تخت خواب", "چوبی", "کلنگ ها", "بیل ها", "تبر ها", "شخم زن", "قلاب ماهی گیری", "سنگ چخماق و استیل", "قیچی", "سطل", "ساعت", "قطب نما", "نقشه", "شالکر باکس", "کاغذ", "کتاب", "کتاب و جوهر", "میله آهنی", "حصار سنگی جهنم", "شمش طلا", "چشم اندر", "میز جادو", "سنگ آتش", "صندوق آخرت", "بیکنی", "انویل", "گلدان", "قالب آیتم", "هویج روی قلاب", "قارچ ناب خورده روی قلاب", "فشفشه", "فشفشه ستاره ای", "طناب", "کف پوش", "صفحه شیشه ای", "طناب. ", "پرچم", "استند زره", "میله اند ", "اند کریستال", "تکه های آهن", "ریل قدرتی", "آتش اردوگاه", "روح آتش اردوگاه", "داربست", "بشکه", "کوره ذوب آهن", "باربیکیو", "میز نقشه برداری", "کامپاستر", "میز فلتچین", "اسمیتینگ تیبل", "برش دهنده سنگ", "سنگ خرد کن", "فانوس", "میز سخنرانی", "میز بافندگی", "کندوی عسل", "زنجیر", "شمش ندرایت", "مشعل روح", "احیا کننده", "سنگ راهنما", "کلاه خودها", "زره ها", "شلوار ها", "چکمه ها", "شمشیر ها", "کمان", "کراس بو", "تیر", "زره اسب", "سپهر", "تیر نشانگر", "تیر جادویی", "مجرا", "پوسته اعتماد", "بطری شیشه ای", "دیگ", "استند دم کردن", "هندوانه طلا", "پودر بلیز", "چشم عنکبوت تبخیر شده", "کرم ماگما", "صفحات فشار", "صفحات فشار دار", "اهرم", "دکمه", "در تله", "پیستون", "استیکی پیستون", "در حصار", "رد استون ریپیدر", "توضیع کننده", "جعبه موسیقی", "ماین کارت", "ماین کارت با فر", "ماین کارت با بمب", "ماین کارت با صندوق", "ریل", "پاور ریل", "ریل رد یاب", "ریل فعال کننده", "مشعل رد استون", "لامپ رد استون", "قلاب سه سیم", "سنسور تشخیص روز", "اندازنده", "قیف", "ارسال کننده سیگنال رد استون", "صندوق تله", "در تله آهنی", "نظاره گر", "هدف", "سنگ درخشان", "بلاک برف", "سنگ آجر", "آجر", "سنگ ماسه", "سنگ ماسه صاف", "سنگ ماسه تزیینی", "بلاک طلا", "بلاک الماس", "بلاک آهن", "بلاک لپیز", "بلاک زمرد", "بلاک زغال", "بلاک پشم", "قفسه کتاب", "بلاک نوت", "بلاک سفالی", "فانوس کدویی", "بمب", "پله چوبی", "پله سنگی", "دیوار سنگی", "بلاک رد استون", "بلاک ندر", "بلاک قرمز ندر", "بلاک ندر قلم زنی شده", "بلاک وارت", "کوآرتز", "بلاک کوآرتز قلم زنی شده", "ستون کوآرتز", "آجر کوآرتز", "دسته گندم", "ماسه سنگ صاف", "شیشه رنگ شده", "گرانیت", "اند استیت", "دیورایت", "گرانیت صیقل خورده", "اند استیت صیقل داده شده", "دیوریت صیقل داده شده", "منشور", "آجر منشور", "منشور تیره", "فانوس دریایی", "خاک درشت", "بلاک اسلایم", "سنگ خزه", "آجر سنگی خزه ای", "آجر سنگی قلم زنی شده", "سنگ ماسه قرمز", "سنگ ماسه قرمز صاف", "سنگ ماسه قرمز قلم زنی شده", "بلاک بنفش", "صدف بنفش", "بلاک ماگما", "بلاک استخوان", "بلاک کلپ بخته", "دسته یخ", "یخ آبی", "بلاک عسل", "بلاک لانه زنبوری", "چوب پوست کنده", "باسیت صیقل داده شده", "سنگ سیاه صیقل داده شده", "سنگ سیاه صیقلی قلم زنی شده", "آجر سنگ سیاه ", "بلاک ندرایت", "کیک", "نان", "شیرنی", "ماسه", "سوپ قارچ", "سیب طلا", "هویج طلا", "دانه کدو", "دانه هندوانه", "بلاک هندوانه", "شکر", "پای کدو", "سوپ خرگوش", "سوپ دید در شب", ""]


var itemsI = [
    "image/1.gif",
    "image/2.png",
    "image/3.png",
    "image/4.png",
    "image/5.png",
    "image/6.png",
    "image/7.png",
    "image/8.png",
    "image/9.png",
    "image/10.gif",
    "image/11.gif",
    "image/12.png",
    "image/13.gif",
    "image/14.png",
    "image/15.png",
    "image/16.png",
    "image/17.gif",
    "image/18.png",
    "image/19.png",
    "image/20.png",
    "image/21.png",
    "image/22.png",
    "image/23.png",
    "image/24.png",
    "image/25.png",
    "image/26.png",
    "image/27.png",
    "image/28.png",
    "image/29.png",
    "image/30.png",
    "image/31.png",
    "image/32.png",
    "image/33.png",
    "image/34.png",
    "image/35.png",
    "image/36.png",
    "image/37.png",
    "image/38.png",
    "image/39.png",
    "image/40.png",
    "image/41.png",
    "image/42.png",
    "image/43.png",
    "image/44.png",
    "image/45.png",
    "image/46.png",
    "image/47.png",
    "image/48.png",
    "image/49.png",
    "image/50.png",
    "image/51.png",
    "image/52.png",
    "image/53.png",
    "image/54.png",
    "image/55.png",
    "image/56.png",
    "image/57.png",
    "image/58.png",
    "image/59.png",
    "image/60.png",
    "image/61.png",
    "image/62.png",
    "image/63.png",
    "image/64.png",
    "image/65.png",
    "image/66.png",
    "image/67.png",
    "image/68.png",
    "image/69.png",
    "image/70.png",
    "image/71.png",
    "image/72.png",
    "image/73.png",
    "image/74.png",
    "image/75.png",
    "image/76.png",
    "image/77.png",
    "image/78.png",
    "image/79.png",
    "image/80.png",
    "image/81.png",
    "image/82.png",
    "image/83.png",
    "image/84.png",
    "image/85.png",
    "image/86.png",
    "image/87.png",
    "image/88.png",
    "image/89.png",
    "image/90.png",
    "image/91.png",
    "image/92.png",
    "image/93.png",
    "image/94.png",
    "image/95.png",
    "image/96.png",
    "image/97.png",
    "image/98.png",
    "image/99.png",
    "image/100.gif",
    "image/101.png",
    "image/102.png",
    "image/103.png",
    "image/104.png",
    "image/105.png",
    "image/106.gif",
    "image/107.png",
    "image/108.gif",
    "image/109.gif",
    "image/110.png",
    "image/111.png",
    "image/112.png",
    "image/113.png",
    "image/114.png",
    "image/115.png",
    "image/116.png",
    "image/117.png",
    "image/118.png",
    "image/119.png",
    "image/120.png",
    "image/121.png",
    "image/122.png",
    "image/123.png",
    "image/124.png",
    "image/125.png",
    "image/126.png",
    "image/127.png",
    "image/128.png",
    "image/129.png",
    "image/130.png",
    "image/131.png",
    "image/132.png",
    "image/133.png",
    "image/134.png",
    "image/135.png",
    "image/136.png",
    "image/137.png",
    "image/138.png",
    "image/139.png",
    "image/140.png",
    "image/141.png",
    "image/142.png",
    "image/143.png",
    "image/144.png",
    "image/145.png",
    "image/146.png",
    "image/147.png",
    "image/148.gif",
    "image/149.gif",
    "image/150.gif",
    "image/151.png",
    "image/152.png",
    "image/153.png",
    "image/154.png",
    "image/155.png",
    "image/156.png",
    "image/157.png",
    "image/158.png",
    "image/159.png",
    "image/160.png",
    "image/161.gif",
    "image/162.gif",
    "image/163.png",
    "image/164.png",
    "image/165.png",
    "image/166.png",
    "image/167.png",
    "image/168.png",
    "image/169.png",
    "image/170.png",
    "image/171.png",
    "image/172.png",
    "image/173.png",
    "image/174.png",
    "image/175.png",
    "image/176.png",
    "image/177.png",
    "image/178.png",
    "image/179.png",
    "image/180.png",
    "image/181.png",
    "image/182.png",
    "image/183.png",
    "image/184.png",
    "image/185.png",
    "image/186.png",
    "image/187.png",
    "image/188.png",
    "image/189.png",
    "image/190.png",
    "image/191.png",
    "image/192.png",
    "image/193.png",
    "image/194.png",
    "image/195.png",
    "image/196.png",
    "image/197.png",
    "image/198.png",
    "image/199.png",
    "image/200.png",
    "image/201.png",
    "image/202.png",
    "image/203.png",
    "image/204.png",
    "image/205.png",
    "image/206.png",
    "image/207.png",
    "image/208.png",
    "image/209.png"
]